name: Continuous Integration

on:
  push:
    branches: ["*"]

env:
  IMAGE_NAME: lucas-leite0112/labfinal

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build . --file Dockerfile.prod --tag ${{ env.IMAGE_NAME }}:latest

      - name: Login to Docker Hub
        run: docker login -u lucas-leite0112 -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image to Docker Hub
        run: docker push ${{ env.IMAGE_NAME }}:latest